eloboosted/urls.py
from django.conf.urls import url, patterns

from . import views

urlpatterns = patterns('',
                       url(r'^$', views.ImageComparison.as_view(), name='categories_for_comparison'),
                       url(r'^comparison/(?P<category_pk>\d+)/$', views.ImageComparison.as_view(), name='comparison'),

                       url(r'^upload/$', views.UploadImage.as_view(), name='upload'),

                       url(r'^rating/$', views.CategoryListForRating.as_view(), name='categories_for_rating'),
                       url(r'^rating/(?P<category_pk>\d+)/$', views.category_sort_for_rating, name='sort_for_rating'),
                       url(r'^rating/(?P<category_pk>\d+)/(?P<filter>\w+)/$', views.Rating.as_view(), name='rating'),

                       url(r'^show_new/$', views.show_new, name='show_new'),

                       )

imagepick/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^', include('eloboosted.urls', namespace='eloboosted')),

    url(r'^accounts/', include('allauth.urls')),

    url(r'^user/', include('usermanagement.urls', namespace='usermanagement')),

    url(r'^i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eloboosted/models.py
import datetime
import os
import uuid

from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.html import format_html
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFit, Transpose
from django.utils.translation import ugettext_lazy as _

from .managers import ImageManager


def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('uploaded_images/{}/{}'.format(
        datetime.date.today().year,
        datetime.date.today().month
    ), filename)


class Category(models.Model):
    name = models.CharField(_('Name'), max_length=100)

    def __str__(self):
        return str(self.name)

    def clean(self):
        if not self.pk:
            if Category.objects.all().count() >= 2:
                raise ValidationError(_('You can\'t create more than 2 categories.'))

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')


class Image(models.Model):
    image = models.ImageField(_('Image'),
                              upload_to=get_file_path)  # TODO: clear CACHE (ask Glebaysan about moderators and admins)
    compressed_image = ImageSpecField(source='image',
                                      processors=[Transpose(), ResizeToFit(900, 600)],
                                      format='JPEG',
                                      options={'quality': 80})
    category = models.ForeignKey(Category, verbose_name=_('Category'))
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              verbose_name=_('Owner'),
                              null=True, blank=True)
    date_created = models.DateTimeField(_('Upload date'), auto_now_add=True)
    current_elo = models.FloatField(_('Current elo'), null=True)
    current_elo_date = models.DateTimeField(_('Latest changing elo date'), null=True)
    moderation_passed = models.BooleanField(_('Moderated'), default=False)

    objects = models.Manager()
    moderated_objects = ImageManager()

    def __str__(self):
        return str(self.date_created)

    def admin_image(self):
        view_original = _('View original')
        try:
            return format_html('<img src="{}" width=100> <a href="{}" target="_blank">{}</a>',
                               self.compressed_image.url,
                               self.image.url,
                               view_original)
        except FileNotFoundError:
            return format_html('<img src="{}" width=100> <a href="{}" target="_blank">{}</a>',
                               self.image.url,
                               self.image.url,
                               view_original)

    admin_image.allow_tags = True
    admin_image.short_description = _('Image')

    def get_absolute_url(self):
        return reverse('eloboosted:comparison', kwargs={'category_pk': self.category.pk})

    def get_elo_count(self):
        return self.elo_set.all().count()

    def get_elo_coefficient(self):
        rez = 20.0
        if self.get_elo_count() <= 30:
            rez = 40.0
        elif self.current_elo >= 2400.0:
            rez = 10.0
        return rez

    def save(self, *args, **kwargs):
        if self.owner is not None:
            if not self.pk and self.owner.get_images_count() < 3:
                super(Image, self).save(*args, **kwargs)
                self.elo_set.create(amount=600)
            elif self.pk and self.owner.get_images_count() <= 3:
                super(Image, self).save(*args, **kwargs)
            else:
                raise ValidationError('user can\'t upload more than 3 images')
        else:
            if not self.pk:
                super(Image, self).save(*args, **kwargs)
                self.elo_set.create(amount=600)
            else:
                super(Image, self).save(*args, **kwargs)

    class Meta:
        verbose_name = _('Image')
        verbose_name_plural = _('Images')
        ordering = ('-current_elo',)


class Elo(models.Model):
    image = models.ForeignKey(Image, verbose_name=_('Image'))
    amount = models.FloatField(_('Amount'))
    date = models.DateTimeField(_('Date'), auto_now_add=True)

    def __str__(self):
        return str(self.amount)

    def save(self, *args, **kwargs):
        super(Elo, self).save(*args, **kwargs)
        self.image.current_elo = self.amount
        self.image.current_elo_date = self.date
        self.image.save()

    class Meta:
        verbose_name = _('Elo')
        verbose_name_plural = _('Elo')
        ordering = ['-date']


class Settings(models.Model):
    name = models.CharField(max_length=100)
    value = models.CharField(max_length=100)

eloboosted/forms.py
from django import forms
from django.core.files.images import get_image_dimensions
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from . import models


class ImageForm(forms.ModelForm):
    def clean_image(self):
        image = self.cleaned_data.get('image', False)
        if image:

            if image._size > settings.MAX_SIZE_FOR_UPLOADED_IMAGE * 1024 * 1024:
                raise forms.ValidationError(
                    _("Image file size must be lower than {size} MB.").format(
                        size=settings.MAX_SIZE_FOR_UPLOADED_IMAGE))

            w, h = get_image_dimensions(image)
            if w * h > settings.PIXELS_LIMIT:
                raise forms.ValidationError(_("Image dimensions are too large."))

            return image
        else:
            raise forms.ValidationError(_('Something went wrong. Try again later.'))

    class Meta:
        model = models.Image
        fields = [
            'image',
            'category'
        ]


class ImageFormAnonymousUser(ImageForm):
    rules = forms.BooleanField(
        initial=False,
        error_messages={'required': _('You have to agree the rules.')},
    )

eloboosted/views.py
import datetime

from django.contrib import messages
from django.core.urlresolvers import reverse
from isoweek import Week
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import View, CreateView, ListView
from django.utils.translation import ugettext as _

from . import models, forms
from . import elo_calculation
from imagepick.utils import log_image_upload


class ImageComparison(View):
    template_name = 'eloboosted/comparison.html'

    def get(self, request, *args, **kwargs):
        category_pk = self.kwargs.get('category_pk', '')

        if not category_pk:
            return render(request, self.template_name, {'category_list': models.Category.objects.all()})

        else:
            category_pk = int(category_pk)
            image_1_pk = request.session.get('image_1_pk', '')
            image_2_pk = request.session.get('image_2_pk', '')
            if not elo_calculation.check_for_category_and_owner(image_1_pk, image_2_pk, category_pk, self.request):
                images_pk_for_comparison = elo_calculation.get_images_pk_to_comparison(category_pk, request.user.pk)
                if images_pk_for_comparison:
                    image_1_pk, image_2_pk = images_pk_for_comparison
                    request.session['image_1_pk'] = image_1_pk
                    request.session['image_2_pk'] = image_2_pk
                else:
                    return HttpResponse('No moderated images in category {}'.format(
                        get_object_or_404(models.Category, pk=category_pk)))

            return render(request, self.template_name,
                          {'image_1': get_object_or_404(models.Image.moderated_objects.select_related('owner'),
                                                        pk=image_1_pk),
                           'image_2': get_object_or_404(models.Image.moderated_objects.select_related('owner'),
                                                        pk=image_2_pk)})

    def post(self, request, *args, **kwargs):
        category_pk = self.kwargs.get('category_pk', '')
        try:
            winner_pk = int(request.POST.get('image_pk', ''))
            if not winner_pk:
                raise ValueError('winner_pk is "{}"'.format(winner_pk))

            image_1_pk = request.session.pop('image_1_pk')
            image_2_pk = request.session.pop('image_2_pk')

            if winner_pk not in [image_1_pk, image_2_pk]:
                raise ValueError('winner_pk should be in request.session')

            loser_pk = image_1_pk if winner_pk == image_2_pk else image_2_pk

            elo_calculation.calculate_elo(winner_pk=winner_pk, loser_pk=loser_pk)
        except KeyError:
            pass
        except ValueError:
            pass

        return HttpResponseRedirect(reverse('eloboosted:comparison', kwargs={'category_pk': category_pk}))


class UploadImage(CreateView):
    template_name = 'eloboosted/upload.html'
    model = models.Image

    def get_form_class(self):
        if self.request.user.is_authenticated():
            return forms.ImageForm
        else:
            return forms.ImageFormAnonymousUser

    def get_context_data(self, **kwargs):
        context = super(UploadImage, self).get_context_data(**kwargs)
        if self.request.session.get('uploaded_image_pk', ''):
            context['has_uploaded_image'] = True
        return context

    def form_valid(self, form):
        if not self.request.session.get('uploaded_image_pk', ''):
            image = form.save(commit=False)
            if self.request.user.is_authenticated():
                image.owner = self.request.user
            else:
                image.owner = None
            image.save()
            log_image_upload(self.request, image)
            if image.owner is None:
                self.request.session['uploaded_image_pk'] = image.pk
                messages.success(self.request,
                                 _('Image successfully uploaded. Sign in and it will show up in your profile.'))
                return HttpResponseRedirect(reverse('account_login'))
            else:
                messages.success(self.request,
                                 _('Image successfully uploaded and sent for moderation.'))
                return HttpResponseRedirect(reverse('usermanagement:profile'))


class CategoryListForRating(ListView):
    template_name = 'eloboosted/categories_for_rating.html'
    model = models.Category


def category_sort_for_rating(request, category_pk):
    category = get_object_or_404(models.Category, pk=category_pk)
    return render(request, 'eloboosted/categories_for_rating.html', {'category_pk': category.pk})


class Rating(ListView):
    template_name = 'eloboosted/rating.html'
    model = models.Image

    def get_queryset(self):
        category_pk = int(self.kwargs.get('category_pk'))
        category = get_object_or_404(models.Category, pk=category_pk)
        multiplier = 2 if self.request.user.is_authenticated() else 1
        objects = None
        start_date = ''
        end_date = ''
        show_count = ''

        if self.kwargs.get('filter') == 'new':
            # now = datetime.date.today()
            # start_date = datetime.datetime.combine(now, datetime.time.min) - datetime.timedelta(days=1)
            # end_date = datetime.datetime.combine(now, datetime.time.max) - datetime.timedelta(days=1)
            start_date = datetime.datetime.now() - datetime.timedelta(days=5)
            end_date = datetime.datetime.now()
            # show_count = 5

        # elif self.kwargs.get('filter') == 'weekly':
        #     current_year, week_number, day_of_week = datetime.date.today().isocalendar()
        #     if day_of_week < 5:
        #         week_number -= 1
        #     start_date = Week(current_year, week_number).friday() - datetime.timedelta(days=7)
        #     end_date = Week(current_year, week_number).thursday()
        #     start_date = datetime.datetime.combine(start_date, datetime.time.min)
        #     end_date = datetime.datetime.combine(end_date, datetime.time.max)
        #     show_count = 10
        #
        # elif self.kwargs.get('filter') == 'monthly':
        #     previous = datetime.date.today().replace(day=1) - datetime.timedelta(days=1)
        #     start_date = datetime.datetime.combine(previous.replace(day=1), datetime.time.min)
        #     end_date = datetime.datetime.combine(previous, datetime.time.max)
        #     show_count = 25

        elif self.kwargs.get('filter') == 'absolute':
            show_count = 100

        if start_date and end_date:
            objects = self.model.moderated_objects.exclude(owner=None).filter(
                date_created__gte=start_date,
                date_created__lte=end_date,
                category=category
            )
        elif show_count:
            objects = self.model.moderated_objects.exclude(owner=None).filter(category=category)[
                      :show_count * multiplier]
        if objects is not None:
            return objects.select_related('owner')
        else:
            raise Http404


def show_new(request):
    if request.user.is_superuser:
        show_new_obj = models.Settings.objects.get(name='show_new')
        show_new_val = show_new_obj.value
        if show_new_val == 'False':
            show_new_obj.value = 'True'
        elif show_new_val == 'True':
            show_new_obj.value = 'False'
        show_new_obj.save()
        return HttpResponseRedirect(reverse('admin:index'))

templates/eloboosted/categories_for_rating.html
{% extends "base_with_banners.html" %}
{% load i18n %}

{% block title %}{% trans 'Rating' %}{% endblock %}

{% block bannered_content %}
    {% if category_pk %}

        <div class="row">
            <div class="col-lg-6">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="rating-monthly text-center">
                            <a href="{% url 'eloboosted:rating' category_pk 'new' %}">{% trans 'New' %}</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="rating-absolute  text-center">
                            <a href="{% url 'eloboosted:rating' category_pk 'absolute' %}">{% trans 'Absolute' %}</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    {% else %}
        {% include 'eloboosted/includes/categories.html' with rating=True %}
    {% endif %}
{% endblock %}

templates/eloboosted/comparison.html
{% extends 'base_with_banners.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% trans 'Comparison' %}{% endblock %}

{% block head %}
    <link href="{% static 'bootsrap-file-input/css/fileinput.css' %}" media="all" rel="stylesheet" type="text/css"/>
{% endblock head %}

{% block bannered_content %}
    {% if category_list %}

        {% include 'eloboosted/includes/categories.html' with comparison=True %}

    {% else %}

        <div class="row">
            {% include 'eloboosted/includes/image_container.html' with image=image_1 for_comparison=True %}
            {% include 'eloboosted/includes/image_container.html' with image=image_2 for_comparison=True %}
        </div>
    {% endif %}
{% endblock %}

{% block js_at_end %}
    <script src="{% static 'js/image_controls.js' %}"></script>
    <script src="{% static 'bootsrap-file-input/js/fileinput.js' %}"></script>
    <script src="{% static 'bootsrap-file-input/js/fileinput_locale_ru.js' %}"></script>
{% endblock %}

{% block modals %}
    {% include 'usermanagement/modals/images_of_user.html' %}
    {% if request.user.likes_balance %}
        {% include 'usermanagement/modals/likes.html' %}
    {% endif %}
    {% include 'usermanagement/modals/send_message.html' %}
{% endblock %}

templates/eloboosted/rating.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans 'Rating' %}{% endblock %}

{% block head %}
    <link href="{% static 'bootsrap-file-input/css/fileinput.css' %}" media="all" rel="stylesheet" type="text/css"/>
{% endblock head %}

{% block content %}
    {% for image in image_list %}
        {% include 'eloboosted/includes/image_container.html' with image=image for_rating=True %}
    {% empty %}
        {% trans 'No images' %}
    {% endfor %}
{% endblock %}

{% block js_at_end %}
    <script src="{% static 'js/image_controls.js' %}"></script>
    <script src="{% static 'js/jquery.lazyload.js' %}"></script>
    <script src="{% static 'bootsrap-file-input/js/fileinput.js' %}"></script>
    <script src="{% static 'bootsrap-file-input/js/fileinput_locale_ru.js' %}"></script>
    <script>
        $(function () {
            $("img.lazy").lazyload();
        });
    </script>
{% endblock %}

{% block modals %}
    {% include 'usermanagement/modals/images_of_user.html' %}
    {% if request.user.likes_balance %}
        {% include 'usermanagement/modals/likes.html' %}
    {% endif %}
    {% include 'usermanagement/modals/send_message.html' %}
{% endblock %}

templates/eloboosted/upload.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% trans 'Upload' %}{% endblock title %}

{% block head %}
    <link href="{% static 'bootsrap-file-input/css/fileinput.css' %}" media="all" rel="stylesheet" type="text/css"/>
{% endblock head %}

{% block content %}
    {% if has_uploaded_image %}
        <h4>{% trans "You already have an uploaded image." %}
            <a href="{% url 'account_login' %}">{% trans "Log In" %}</a> {% trans "and it will show up in your profile." %}</h4>
    {% else %}
        {% if request.user.get_images_count < 3 or not request.user.is_authenticated %}
            <div class="panel panel-default">
                <div class="panel-body">
                    <form action="" method="post" enctype="multipart/form-data">

                        {% include 'forms/upload.html' %}

                        <button type="submit" class="btn btn-primary">{% trans 'Upload' %}</button>
                    </form>
                </div>
            </div>

        {% else %}
            <h4>{% trans "You can't upload more than 3 images." %}</h4>
        {% endif %}
    {% endif %}
{% endblock %}

{{% block js_at_end %}
    <script src="{% static 'bootsrap-file-input/js/fileinput.js' %}"></script>
    <script src="{% static 'bootsrap-file-input/js/fileinput_locale_ru.js' %}"></script>
{% endblock js_at_end %}