imagepick/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^', include('eloboosted.urls', namespace='eloboosted')),

    url(r'^accounts/', include('allauth.urls')),

    url(r'^user/', include('usermanagement.urls', namespace='usermanagement')),

    url(r'^i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usermanagement/urls.py
from django.conf.urls import url, patterns, include
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = patterns('',
                       url(r'^have-18-age/$', views.have_18_age, name='have_18_age'),

                       url(r'^images/$', views.ViewAllImagesOfUser.as_view(), name='images_of_user'),  # AJAX!

                       url(r'^send-message/$', login_required(views.send_message), name='send_message'),  # AJAX!

                       url(r'^check-on-login/$', login_required(views.check_on_login), name='check_on_login'),

                       url(r'^check-on-logout/$', views.check_on_logout, name='check_on_logout'),

                       url(r'^paypal/', include('paypal.standard.ipn.urls')),

                       url(r'^profile/$', login_required(views.Profile.as_view()), name='profile'),

                       url(r'^likes/$', login_required(views.LikesPage.as_view()), name='likes'),

                       url(r'^transfer-likes/$', login_required(views.transfer_likes), name='transfer_likes'),  # AJAX!

                       url(r'^upload/$', login_required(views.UploadImageFromProfile.as_view()), name='upload'),

                       url(r'^chat/$', login_required(views.ChatPage.as_view()), name='chat_page'),

                       url(r'^chat/(?P<user_pk>\d+)/$', login_required(views.Chat.as_view()), name='chat'),

                       url(r'^delete/(?P<pk>\d+)/$', login_required(views.delete_image), name='delete'),

                       url(r'^change-privacy-settings/$', login_required(views.privacy_settings),
                           name='change_privacy_settings'),

                       url(r'^favorites/$', login_required(views.FavoriteImages.as_view()), name='favorites'),

                       url(r'^favorite/add/$', login_required(views.toggle_favorite), {'operation': 'add'},
                           name='add_to_favorite'),  # AJAX!

                       url(r'^favorite/remove/$', login_required(views.toggle_favorite), {'operation': 'remove'},
                           name='remove_to_favorite'
                           ),  # AJAX!

                       )

eloboosted/models.py
import datetime
import os
import uuid

from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.html import format_html
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFit, Transpose
from django.utils.translation import ugettext_lazy as _

from .managers import ImageManager


def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('uploaded_images/{}/{}'.format(
        datetime.date.today().year,
        datetime.date.today().month
    ), filename)


class Category(models.Model):
    name = models.CharField(_('Name'), max_length=100)

    def __str__(self):
        return str(self.name)

    def clean(self):
        if not self.pk:
            if Category.objects.all().count() >= 2:
                raise ValidationError(_('You can\'t create more than 2 categories.'))

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')


class Image(models.Model):
    image = models.ImageField(_('Image'),
                              upload_to=get_file_path)  # TODO: clear CACHE (ask Glebaysan about moderators and admins)
    compressed_image = ImageSpecField(source='image',
                                      processors=[Transpose(), ResizeToFit(900, 600)],
                                      format='JPEG',
                                      options={'quality': 80})
    category = models.ForeignKey(Category, verbose_name=_('Category'))
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              verbose_name=_('Owner'),
                              null=True, blank=True)
    date_created = models.DateTimeField(_('Upload date'), auto_now_add=True)
    current_elo = models.FloatField(_('Current elo'), null=True)
    current_elo_date = models.DateTimeField(_('Latest changing elo date'), null=True)
    moderation_passed = models.BooleanField(_('Moderated'), default=False)

    objects = models.Manager()
    moderated_objects = ImageManager()

    def __str__(self):
        return str(self.date_created)

    def admin_image(self):
        view_original = _('View original')
        try:
            return format_html('<img src="{}" width=100> <a href="{}" target="_blank">{}</a>',
                               self.compressed_image.url,
                               self.image.url,
                               view_original)
        except FileNotFoundError:
            return format_html('<img src="{}" width=100> <a href="{}" target="_blank">{}</a>',
                               self.image.url,
                               self.image.url,
                               view_original)

    admin_image.allow_tags = True
    admin_image.short_description = _('Image')

    def get_absolute_url(self):
        return reverse('eloboosted:comparison', kwargs={'category_pk': self.category.pk})

    def get_elo_count(self):
        return self.elo_set.all().count()

    def get_elo_coefficient(self):
        rez = 20.0
        if self.get_elo_count() <= 30:
            rez = 40.0
        elif self.current_elo >= 2400.0:
            rez = 10.0
        return rez

    def save(self, *args, **kwargs):
        if self.owner is not None:
            if not self.pk and self.owner.get_images_count() < 3:
                super(Image, self).save(*args, **kwargs)
                self.elo_set.create(amount=600)
            elif self.pk and self.owner.get_images_count() <= 3:
                super(Image, self).save(*args, **kwargs)
            else:
                raise ValidationError('user can\'t upload more than 3 images')
        else:
            if not self.pk:
                super(Image, self).save(*args, **kwargs)
                self.elo_set.create(amount=600)
            else:
                super(Image, self).save(*args, **kwargs)

    class Meta:
        verbose_name = _('Image')
        verbose_name_plural = _('Images')
        ordering = ('-current_elo',)


class Elo(models.Model):
    image = models.ForeignKey(Image, verbose_name=_('Image'))
    amount = models.FloatField(_('Amount'))
    date = models.DateTimeField(_('Date'), auto_now_add=True)

    def __str__(self):
        return str(self.amount)

    def save(self, *args, **kwargs):
        super(Elo, self).save(*args, **kwargs)
        self.image.current_elo = self.amount
        self.image.current_elo_date = self.date
        self.image.save()

    class Meta:
        verbose_name = _('Elo')
        verbose_name_plural = _('Elo')
        ordering = ['-date']


class Settings(models.Model):
    name = models.CharField(max_length=100)
    value = models.CharField(max_length=100)

usermanagement/views.py
import json

from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, TemplateView, CreateView
from paypal.standard.ipn.signals import valid_ipn_received
from paypal.standard.models import ST_PP_COMPLETED
from django.utils.translation import ugettext as _

from eloboosted import models as eloboosted_models
from eloboosted import forms as eloboosted_forms
from . import models
from .forms import MessageForm
from imagepick.utils import log_image_upload
from .mixins import ChatUsersMixin

FULL_SITE = 'http://' + get_current_site(None).domain


def have_18_age(request):
    request.session['have_18_age'] = 'True'
    messages.info(request,
                  _('Using this website, you agree to the use cookies to improve the level of service.'))
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class ViewAllImagesOfUser(ListView):
    template_name = 'usermanagement/ajax/images_of_user.html'
    model = eloboosted_models.Image

    def get_queryset(self):
        image = get_object_or_404(self.model.moderated_objects, pk=self.request.GET.get('image_pk'))
        owner = image.owner
        if owner.allow_see_all_images:
            return self.model.moderated_objects.filter(owner=owner).select_related('owner')
        else:
            raise Http404


def send_message(request):
    if request.is_ajax():
        try:
            form = MessageForm(request.POST, request.FILES)
            if form.is_valid():
                image_pk = int(request.POST.get('image_pk'))
                image = get_object_or_404(eloboosted_models.Image.moderated_objects, pk=image_pk)
                owner = image.owner
                full_form = form.save(commit=False)
                full_form.sender = request.user
                full_form.receiver = owner
                full_form.save()
                status = 'success'
                message = _('Message successfully sent!')
            else:
                status = 'error'
                message = _('Enter message text.')
        except:
            status = 'error'
            message = _('Enter a message and/or upload an image.')

        return HttpResponse(json.dumps({
            'message': message,
            'status': status
        }))


class Profile(TemplateView):
    template_name = 'usermanagement/profile.html'

    def get_context_data(self, **kwargs):
        context = super(Profile, self).get_context_data(**kwargs)
        context['upload_form'] = eloboosted_forms.ImageForm
        return context


class ChatPage(ChatUsersMixin, TemplateView):
    template_name = 'usermanagement/chat.html'


class UploadImageFromProfile(CreateView):
    template_name = 'usermanagement/profile.html'
    form_class = eloboosted_forms.ImageForm

    def get_context_data(self, **kwargs):
        context = super(UploadImageFromProfile, self).get_context_data(**kwargs)
        context['upload_form'] = context.pop('form')
        return context

    def form_valid(self, form):
        image = form.save(commit=False)
        image.owner = self.request.user
        image.save()
        log_image_upload(self.request, image)
        messages.success(self.request, _('Image successfully uploaded and sent for moderation.'))
        return HttpResponseRedirect(reverse('usermanagement:profile'))

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        context['upload_form_invalid'] = True
        return self.render_to_response(context)


def delete_image(request, pk):
    image = get_object_or_404(eloboosted_models.Image, pk=pk)
    if image not in request.user.image_set.all():
        return HttpResponse('it\'s not your image!')
    image.owner = None
    image.save()
    messages.success(request, _('Image successfully removed.'))
    return HttpResponseRedirect(reverse('usermanagement:profile'))


def privacy_settings(request):
    allow_messages = False
    allow_see_all_images = False
    has_changed = False
    if request.POST.get('allow_messages', ''):
        allow_messages = True
    if request.POST.get('allow_see_all_images', ''):
        allow_see_all_images = True
    if allow_messages != request.user.allow_messages:
        has_changed = True
        request.user.allow_messages = allow_messages
    if allow_see_all_images != request.user.allow_see_all_images:
        has_changed = True
        request.user.allow_see_all_images = allow_see_all_images
    if has_changed:
        request.user.save()
    messages.success(request, _('Privacy settings saved.'))
    return HttpResponseRedirect(reverse('usermanagement:profile'))


class FavoriteImages(TemplateView):
    template_name = 'usermanagement/favorites.html'


def toggle_favorite(request, operation):
    if request.is_ajax():
        image_pk = request.POST.get('image_pk', '')
        if image_pk:
            image = get_object_or_404(eloboosted_models.Image.moderated_objects, pk=image_pk)
            if image.owner != request.user:
                status = 'error'
                if operation == 'add':
                    if image not in request.user.favorite_images.all():
                        request.user.favorite_images.add(image)
                        status = 'success'
                elif operation == 'remove':
                    if image in request.user.favorite_images.all():
                        request.user.favorite_images.remove(image)
                        status = 'success'
                return HttpResponse(json.dumps({'status': status}))


class Chat(ChatUsersMixin, ListView):
    template_name = 'usermanagement/chat.html'
    model = models.Message
    context_object_name = 'chat_messages'
    companion = None
    form = MessageForm

    def get_context_data(self, **kwargs):
        context = super(Chat, self).get_context_data(**kwargs)
        context['companion'] = self.companion
        if 'form' in kwargs:
            context['form'] = kwargs['form']
        else:
            context['form'] = self.form
        return context

    def post(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        form = self.form(request.POST, request.FILES)
        if form.is_valid():
            msg = form.save(commit=False)
            msg.sender = self.request.user
            msg.receiver = get_object_or_404(models.MyUser, pk=self.kwargs.get('user_pk'))
            msg.save()
            return HttpResponseRedirect(reverse('usermanagement:chat', kwargs={'user_pk': self.kwargs.get('user_pk')}))
        else:
            context = self.get_context_data(form=form)
            return self.render_to_response(context)

    def get_queryset(self):
        companion = get_object_or_404(models.MyUser, pk=self.kwargs.get('user_pk'))
        user = self.request.user

        conversation_messages = self.model.objects.filter(
            (Q(sender=user) & Q(receiver=companion)) | (Q(sender=companion) & Q(receiver=user)))

        if not conversation_messages or companion == user:
            raise Http404
        self.companion = companion
        self.model.objects.filter(Q(sender=companion) & Q(receiver=user) & Q(is_read=False)).update(is_read=True)
        return conversation_messages


def transfer_likes(request):
    if request.is_ajax():
        try:
            amount = int(request.POST.get('amount'))
            if amount <= 0:
                raise ValueError('amount must be positive!')
            if amount > request.user.likes_balance:
                raise ValueError('can\'t donate more than you\'ve got!')
            image = get_object_or_404(eloboosted_models.Image.moderated_objects, pk=request.POST.get('image_pk'))
            owner = image.owner
            models.LikesTransfer.objects.create(
                from_user=request.user,
                to_user=owner,
                amount=amount
            )
            status = 'success'
            message = _('Success!')
        except Exception as e:
            message = _('Amount of likes must be greater than 0 and lower than ')
            status = 'error'

        return HttpResponse(json.dumps({'status': status, 'message': message,
                                        }))


def check_on_login(request):
    request.session.pop('image_1_pk', None)
    request.session.pop('image_2_pk', None)
    return HttpResponseRedirect(reverse('usermanagement:profile'))


def check_on_logout(request):
    request.session['have_18_age'] = 'True'
    return HttpResponseRedirect(reverse('account_login'))


class LikesPage(TemplateView):
    template_name = 'usermanagement/likes.html'


def paypal_callback_success(sender, **kwargs):
    ipn_obj = sender
    if ipn_obj.payment_status == ST_PP_COMPLETED:
        user_pk = int(ipn_obj.custom)
        user = models.MyUser.objects.get(pk=user_pk)
        amount = ipn_obj.quantity
        models.LikesBuying.objects.create(
            payment=ipn_obj,
            user=user,
            amount=amount
        )


valid_ipn_received.connect(paypal_callback_success)

templates/usermanagement/chat.html
{% extends "usermanagement/profile_base.html" %}

{% load widget_tweaks %}
{% load static %}
{% load usermanagement_tags %}
{% load i18n %}
{% block title %}{% trans "Chat" %}{% endblock title %}

{% block head %}
    <link href="{% static 'bootsrap-file-input/css/fileinput.css' %}" media="all" rel="stylesheet" type="text/css"/>
{% endblock head %}


{% block content %}

    <div class="row">
        <div class="col-lg-8 messages">
            <h3>
                {% if chat_messages %}{% trans "Chatting with user" %} {{ companion }}
                {% else %}{% trans "Chat" %}{% endif %}
            </h3>
            <hr>

            {% if chat_messages %}

                <div class="">
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'forms/includes/form_non_field_errors.html' %}
                        <table>
                            <tr>
                                <td colspan="2">
                                    <div class="form-group {% if form.text.errors %}has-error{% endif %}">
                                        {{ form.text|add_class:'form-control bg-white'|attr:'rows:4'|attr:'cols:100' }}
                                        {% include 'forms/includes/form_field_errors.html' with form_field=form.text %}
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    {% include 'forms/includes/file_field.html' %}
                                </td>

                                <td>
                                    <button type="submit" class="btn btn-primary pull-right">{% trans "Send" %}</button>
                                </td>
                        </table>
                    </form>
                </div>

                <div class="well well-chat">
                    {% load endless %}
                    {% paginate 10 chat_messages %}

                    {% for message in chat_messages %}
                        <div class="row">
                            <div class="{% if message.receiver == request.user %}received-message{% else %}sent-message{% endif %}">
                                {{ message.date_sent }}<br>{{ message.text }}
                                {% if message.attached_image %}
                                    <div class="panel panel-default"><div class="panel-body"><img src="{{ message.attached_image.url }}" class="img-responsive"></div></div>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                {% show_pages %}
                </div>

            {% else %}
                {% trans "Select a user" %}
            {% endif %}
        </div>

        <div class="col-lg-4 friends-name">
            <h3>{% trans "Users" %}</h3>
            <hr>
            <div class="">
                {% for user in chat_users %}
                    <a href="{% url 'usermanagement:chat' user.pk %}">{{ user }}
                        {% if user|unread_msg_count:request %}
                            <span class="badge">{{ user|unread_msg_count:request }}</span>
                        {% endif %}
                    </a><br>
                {% empty %}
                    {% trans "No users to chat with." %}
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock content %}

{% block js_at_end %}
    <script src="{% static 'bootsrap-file-input/js/fileinput.js' %}"></script>
    <script src="{% static 'bootsrap-file-input/js/fileinput_locale_ru.js' %}"></script>
{% endblock js_at_end %}

templates/usermanagement/favorites.html
{% extends "usermanagement/profile_base.html" %}

{% load static %}
{% load i18n %}

{% block title %}{% trans "Favorites" %}{% endblock %}

{% block head %}
    <link href="{% static 'bootsrap-file-input/css/fileinput.css' %}" media="all" rel="stylesheet" type="text/css"/>
{% endblock head %}

{% block content %}
    {% for image in request.user.get_favorite_images %}
        {% include 'eloboosted/includes/image_container.html' with for_rating=True %}
    {% empty %}
        {% trans "No favorites" %}
    {% endfor %}

{% endblock content %}

{% block js_at_end %}
    <script src="{% static 'js/image_controls.js' %}"></script>
    <script src="{% static 'js/jquery.lazyload.js' %}"></script>
    <script src="{% static 'bootsrap-file-input/js/fileinput.js' %}"></script>
    <script src="{% static 'bootsrap-file-input/js/fileinput_locale_ru.js' %}"></script>
    <script>
        $(function () {
            $("img.lazy").lazyload();
        });
    </script>
{% endblock js_at_end %}

{% block modals %}
    {% include 'usermanagement/modals/images_of_user.html' %}
    {% if request.user.likes_balance %}
        {% include 'usermanagement/modals/likes.html' %}
    {% endif %}
    {% include 'usermanagement/modals/send_message.html' %}
{% endblock modals %}

templates/usermanagement/likes.html
{% extends 'usermanagement/profile_base.html' %}
{% load i18n %}

{% block title %}{% trans "Likes" %}{% endblock title %}

{% block content %}

    <div>
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#received" aria-controls="received" role="tab"
                                                      data-toggle="tab">{% trans "Received" %}</a>
            </li>
            <li role="presentation"><a href="#sent" aria-controls="sent" role="tab"
                                       data-toggle="tab">{% trans "Sent" %}</a>
            </li>
            <li role="presentation"><a href="#bought" aria-controls="bought" role="tab"
                                       data-toggle="tab">{% trans "Bought" %}</a></li>
            <li role="presentation"><a href="#out" aria-controls="out" role="tab"
                                       data-toggle="tab">{% trans "Out" %}</a></li>
        </ul>

        <div class="tab-content">
            <div role="tabpanel" class="tab-pane fade in active" id="received">
                {% include 'usermanagement/includes/like_table.html' with like_qs=request.user.received_likes.all %}
            </div>
            <div role="tabpanel" class="tab-pane fade" id="sent">
                {% include 'usermanagement/includes/like_table.html' with like_qs=request.user.sent_likes.all %}
            </div>
            <div role="tabpanel" class="tab-pane fade" id="bought">
                {% include 'usermanagement/includes/like_table.html' with like_qs=request.user.likesbuying_set.all %}
            </div>
            <div role="tabpanel" class="tab-pane fade" id="out">
                {% include 'usermanagement/includes/like_table.html' with like_qs=request.user.likesout_set.all %}
            </div>
        </div>

    </div>

    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#buy_likes_modal">
        {% trans "Buy likes" %}
    </button>

    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#out_likes_modal">
        {% trans "Out likes" %}
    </button>
{% endblock content %}

{% block modals %}
    {% include 'usermanagement/modals/buy_likes.html' %}
    {% include 'usermanagement/modals/out_likes.html' %}
{% endblock modals %}

templates/usermanagement/profile.html
{% extends "usermanagement/profile_base.html" %}

{% load static %}
{% load i18n %}

{% block title %}{% trans "Profile" %}{% endblock %}

{% block head %}
    <link href="{% static 'bootsrap-file-input/css/fileinput.css' %}" media="all" rel="stylesheet" type="text/css"/>
{% endblock head %}

{% block content %}
    <div class="row">
        {% include 'usermanagement/includes/image_container_profile.html' with image=request.user.image_set.all.0 %}
        {% include 'usermanagement/includes/image_container_profile.html' with image=request.user.image_set.all.1 %}
        {% include 'usermanagement/includes/image_container_profile.html' with image=request.user.image_set.all.2 %}
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="set-private">
                <p class="text-center"><a class="btn btn-default btn-primary btn-private" data-toggle="collapse"
                                          href="#collapsePrivacy" aria-expanded="false"
                                          aria-controls="collapsePrivacy">{% trans "Privacy settings" %}</a></p>

                <div id="collapsePrivacy" class="collapse well">
                    <form action="{% url 'usermanagement:change_privacy_settings' %}" method="post">
                        {% csrf_token %}
                        <label><input type="checkbox" name="allow_messages"
                                      {% if request.user.allow_messages %}checked{% endif %}>{% trans "Allow users to send you messages" %}
                        </label><br>
                        <label><input type="checkbox" name="allow_see_all_images"
                                      {% if request.user.allow_see_all_images %}checked{% endif %}>{% trans "Allow users to view your images" %}
                        </label><br>
                        <input type="submit" value="{% trans "Save" %}" class="btn btn-primary">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block js_at_end %}
    <script src="{% static 'js/profile.js' %}"></script>
    <script src="{% static 'bootsrap-file-input/js/fileinput.js' %}"></script>
    <script src="{% static 'bootsrap-file-input/js/fileinput_locale_ru.js' %}"></script>
{% endblock js_at_end %}

{% block modals %}
    {% if request.user.get_images_count < 3 %}
        {% include 'usermanagement/modals/upload.html' %}
    {% endif %}
    {% include 'usermanagement/modals/delete.html' %}
{% endblock modals %}

templates/usermanagement/profile_base.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block before_content %}
    <div class="row">
        <div class="col-lg-12">
            <p class="text-center">
                <a href="{% url 'usermanagement:profile' %}">
                    <img src="{% static 'img/profile.png' %}" title="{% trans "Profile" %}">
                </a>

                <a href="{% url 'usermanagement:chat_page' %}">
                    <img src="{% static 'img/mes-profile.png' %}" title="{% trans "Messages" %}">
                </a>
                <span class="badge">{{ request.user.get_unread_messages_count }}</span>

                <a href="{% url 'usermanagement:favorites' %}">
                    <img src="{% static 'img/fav-profile.png' %}" title="{% trans "Favorites" %}">
                </a>
                <span class="badge">{{ request.user.favorite_images.count }}</span>

                <a href="{% url 'usermanagement:likes' %}">
                    <img src="{% static 'img/like-profile.png' %}" title="{% trans "Likes" %}">
                </a>
                <span class="badge">{{ request.user.likes_balance }}</span>
            </p>
        </div>
    </div>
{% endblock before_content %}