eloboosted/urls.py
from django.conf.urls import url, patterns

from . import views

urlpatterns = patterns('',
                       url(r'^$', views.ImageComparison.as_view(), name='categories_for_comparison'),
                       url(r'^comparison/(?P<category_pk>\d+)/$', views.ImageComparison.as_view(), name='comparison'),

                       url(r'^upload/$', views.UploadImage.as_view(), name='upload'),

                       url(r'^rating/$', views.CategoryListForRating.as_view(), name='categories_for_rating'),
                       url(r'^rating/(?P<category_pk>\d+)/$', views.category_sort_for_rating, name='sort_for_rating'),
                       url(r'^rating/(?P<category_pk>\d+)/(?P<filter>\w+)/$', views.Rating.as_view(), name='rating'),

                       url(r'^show_new/$', views.show_new, name='show_new'),

                       )

imagepick/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^', include('eloboosted.urls', namespace='eloboosted')),

    url(r'^accounts/', include('allauth.urls')),

    url(r'^user/', include('usermanagement.urls', namespace='usermanagement')),

    url(r'^i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usermanagement/urls.py
from django.conf.urls import url, patterns, include
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = patterns('',
                       url(r'^have-18-age/$', views.have_18_age, name='have_18_age'),

                       url(r'^images/$', views.ViewAllImagesOfUser.as_view(), name='images_of_user'),  # AJAX!

                       url(r'^send-message/$', login_required(views.send_message), name='send_message'),  # AJAX!

                       url(r'^check-on-login/$', login_required(views.check_on_login), name='check_on_login'),

                       url(r'^check-on-logout/$', views.check_on_logout, name='check_on_logout'),

                       url(r'^paypal/', include('paypal.standard.ipn.urls')),

                       url(r'^profile/$', login_required(views.Profile.as_view()), name='profile'),

                       url(r'^likes/$', login_required(views.LikesPage.as_view()), name='likes'),

                       url(r'^transfer-likes/$', login_required(views.transfer_likes), name='transfer_likes'),  # AJAX!

                       url(r'^upload/$', login_required(views.UploadImageFromProfile.as_view()), name='upload'),

                       url(r'^chat/$', login_required(views.ChatPage.as_view()), name='chat_page'),

                       url(r'^chat/(?P<user_pk>\d+)/$', login_required(views.Chat.as_view()), name='chat'),

                       url(r'^delete/(?P<pk>\d+)/$', login_required(views.delete_image), name='delete'),

                       url(r'^change-privacy-settings/$', login_required(views.privacy_settings),
                           name='change_privacy_settings'),

                       url(r'^favorites/$', login_required(views.FavoriteImages.as_view()), name='favorites'),

                       url(r'^favorite/add/$', login_required(views.toggle_favorite), {'operation': 'add'},
                           name='add_to_favorite'),  # AJAX!

                       url(r'^favorite/remove/$', login_required(views.toggle_favorite), {'operation': 'remove'},
                           name='remove_to_favorite'
                           ),  # AJAX!

                       )

templates/base.html
{% load static %}
{% load eloboosted_tags %}
{% load i18n %}

<!DOCTYPE html>

<html lang="ru">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% trans "Main Page" %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap-3.3.5-dist/css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/business-casual.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block head %}{% endblock %}
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
            <a class="navbar-brand" href="{% url 'eloboosted:categories_for_comparison' %}"><img
                    src="{% static 'img/logo.png' %}"></a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'eloboosted:upload' %}">{% trans "Add" %}</a>
                </li>
                <li>
                    <a href="{% url 'eloboosted:categories_for_comparison' %}">{% trans "Comparison" %}</a>
                </li>
                <li>
                    <a href="{% url 'eloboosted:categories_for_rating' %}">{% trans "Rating" %}</a>
                </li>

                {% if request.user.is_authenticated %}

                    <li>
                        <a href="
                                {% if request.user.get_unread_messages_count %}
                                {% url 'usermanagement:chat_page' %}
                                {% else %}
                                {% url 'usermanagement:profile' %}
                                {% endif %}">
                            {{ request.user }}
                            {% if request.user.get_unread_messages_count %}
                                <span class="badge">{{ request.user.get_unread_messages_count }}</span>
                            {% endif %}
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
                    </li>

                {% else %}
                    <li>
                        <a href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                    </li>
                {% endif %}
                <li>
                    <a href="">{% trans "About" %}</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>
{% block after_nav %}{% endblock after_nav %}

{% if messages %}
    <ul class="list-unstyled alert-messages">
        {% for message in messages %}
            {% get_bootstrap_alert_msg_css_name message.tags as alert_tag %}
            <li class="alert alert-{{ alert_tag }} alert-dismissible text-center">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                {{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% block messages %}{% endblock messages %}

<div class="container">
    {% block before_content %}{% endblock before_content %}
    {% block content %}{% endblock content %}
</div>

<footer>
    <div class="container">
        <hr>
        <div class="row">
            <div class="col-lg-12 text-center">
                <ul class="list-inline">
                    <li><a href="" class="lang-ico ru"></a></li>
                    <li><a href="" class="lang-ico en"></a></li>
                </ul>

            <br>

                <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}"/>
                    <select name="language" onchange="this.form.submit()">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %}
                                    selected="selected"{% endif %}>
                                {{ language.name_local }}
                            </option>
                        {% endfor %}
                    </select>
                </form>
            </div>
        </div>
    </div>
</footer>


<script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="{% static 'bootstrap-3.3.5-dist/js/bootstrap.js' %}"></script>


<script src="{% static 'js/index.js' %}"></script>
<script type="text/javascript">
    setBaseUrl('{{ BASE_URL }}');
    setMaxFileSize({{ MAX_FILE_SIZE }});
</script>
<script>
    function reloadChosenSelect() {
        try {
            $(".chosen-select").chosen({
                width: '100%',
                disable_search_threshold: 5,
                no_results_text: '{% trans "No results found" %}'
            });

        }
        catch (e) {
        }
    }

    $(reloadChosenSelect);

    function feloadFileInputs() {
        try {
            $(".file-input").fileinput({
                browseLabel: "{% trans "Browse images..." %}",
                removeLabel: "{% trans "Remove" %}",
                browseIcon: "<i class=\"glyphicon glyphicon-picture\"></i> ",
                showCaption: false,
                showUpload: false,
                allowedFileTypes: ['image'],
                allowedPreviewTypes: ['image'],
                maxFileSize: MAX_FILE_SIZE * 1024
            });
        }
        catch (e) {
        }
    }
    $(feloadFileInputs);
</script>
{% block js_at_end %}{% endblock %}


{% if show_18_age_modal %}
    {% include 'usermanagement/modals/have_18_age.html' %}
{% endif %}

{% block modals %}{% endblock %}
</body>
</html>

templates/base_with_banners.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <section class="banner">
                <p class="text-center banner-p">Тест сервиса<br> Группа МО-041 и люди которые с ними бухали</p>
            </section>
        </div>
    </div>
    {% block bannered_content %}{% endblock %}
    <div class="row">
        <div class="col-lg-12">
            <section class="banner">
                <p class="text-center banner-p">Place for your ads</p>
            </section>
        </div>
    </div>
{% endblock %}