imagepick/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^', include('eloboosted.urls', namespace='eloboosted')),

    url(r'^accounts/', include('allauth.urls')),

    url(r'^user/', include('usermanagement.urls', namespace='usermanagement')),

    url(r'^i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usermanagement/urls.py
from django.conf.urls import url, patterns, include
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = patterns('',
                       url(r'^have-18-age/$', views.have_18_age, name='have_18_age'),

                       url(r'^images/$', views.ViewAllImagesOfUser.as_view(), name='images_of_user'),  # AJAX!

                       url(r'^send-message/$', login_required(views.send_message), name='send_message'),  # AJAX!

                       url(r'^check-on-login/$', login_required(views.check_on_login), name='check_on_login'),

                       url(r'^check-on-logout/$', views.check_on_logout, name='check_on_logout'),

                       url(r'^paypal/', include('paypal.standard.ipn.urls')),

                       url(r'^profile/$', login_required(views.Profile.as_view()), name='profile'),

                       url(r'^likes/$', login_required(views.LikesPage.as_view()), name='likes'),

                       url(r'^transfer-likes/$', login_required(views.transfer_likes), name='transfer_likes'),  # AJAX!

                       url(r'^upload/$', login_required(views.UploadImageFromProfile.as_view()), name='upload'),

                       url(r'^chat/$', login_required(views.ChatPage.as_view()), name='chat_page'),

                       url(r'^chat/(?P<user_pk>\d+)/$', login_required(views.Chat.as_view()), name='chat'),

                       url(r'^delete/(?P<pk>\d+)/$', login_required(views.delete_image), name='delete'),

                       url(r'^change-privacy-settings/$', login_required(views.privacy_settings),
                           name='change_privacy_settings'),

                       url(r'^favorites/$', login_required(views.FavoriteImages.as_view()), name='favorites'),

                       url(r'^favorite/add/$', login_required(views.toggle_favorite), {'operation': 'add'},
                           name='add_to_favorite'),  # AJAX!

                       url(r'^favorite/remove/$', login_required(views.toggle_favorite), {'operation': 'remove'},
                           name='remove_to_favorite'
                           ),  # AJAX!

                       )

usermanagement/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.files.images import get_image_dimensions
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from . import models


class SignupForm(forms.ModelForm):
    rules = forms.BooleanField(
        initial=False,
        error_messages={'required': _('You have to agree the rules.')},
    )

    class Meta:
        model = get_user_model()
        fields = ['sex', 'age', 'country']

    def signup(self, request, user):
        user.save()


class MessageForm(forms.ModelForm):
    def clean_attached_image(self):
        image = self.cleaned_data.get('attached_image', False)
        if image:

            if image._size > settings.MAX_SIZE_FOR_UPLOADED_IMAGE * 1024 * 1024:
                raise forms.ValidationError(
                    _("Image file size must be lower than {size} MB.").format(size=settings.MAX_SIZE_FOR_UPLOADED_IMAGE))

            w, h = get_image_dimensions(image)
            if w * h > settings.PIXELS_LIMIT:
                raise forms.ValidationError(_("Image dimensions are too large."))

            return image

    def clean(self):
        cleaned_data = super(MessageForm, self).clean()
        image = cleaned_data.get('attached_image', '')
        text = cleaned_data.get('text', '')
        if not image and not text:
            raise forms.ValidationError(_('Enter a message and/or upload an image.'))

    class Meta:
        model = models.Message
        fields = ['text', 'attached_image']

#
# class GiveUserTheMoneyForm(forms.ModelForm):
#     class Meta:
#         model = models.GiveUserTheMoney
#         fields = [
#             'name',
#             'number',
#             'date',
#             'cvc',
#             'amount'
#         ]

usermanagement/views.py
import json

from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, TemplateView, CreateView
from paypal.standard.ipn.signals import valid_ipn_received
from paypal.standard.models import ST_PP_COMPLETED
from django.utils.translation import ugettext as _

from eloboosted import models as eloboosted_models
from eloboosted import forms as eloboosted_forms
from . import models
from .forms import MessageForm
from imagepick.utils import log_image_upload
from .mixins import ChatUsersMixin

FULL_SITE = 'http://' + get_current_site(None).domain


def have_18_age(request):
    request.session['have_18_age'] = 'True'
    messages.info(request,
                  _('Using this website, you agree to the use cookies to improve the level of service.'))
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class ViewAllImagesOfUser(ListView):
    template_name = 'usermanagement/ajax/images_of_user.html'
    model = eloboosted_models.Image

    def get_queryset(self):
        image = get_object_or_404(self.model.moderated_objects, pk=self.request.GET.get('image_pk'))
        owner = image.owner
        if owner.allow_see_all_images:
            return self.model.moderated_objects.filter(owner=owner).select_related('owner')
        else:
            raise Http404


def send_message(request):
    if request.is_ajax():
        try:
            form = MessageForm(request.POST, request.FILES)
            if form.is_valid():
                image_pk = int(request.POST.get('image_pk'))
                image = get_object_or_404(eloboosted_models.Image.moderated_objects, pk=image_pk)
                owner = image.owner
                full_form = form.save(commit=False)
                full_form.sender = request.user
                full_form.receiver = owner
                full_form.save()
                status = 'success'
                message = _('Message successfully sent!')
            else:
                status = 'error'
                message = _('Enter message text.')
        except:
            status = 'error'
            message = _('Enter a message and/or upload an image.')

        return HttpResponse(json.dumps({
            'message': message,
            'status': status
        }))


class Profile(TemplateView):
    template_name = 'usermanagement/profile.html'

    def get_context_data(self, **kwargs):
        context = super(Profile, self).get_context_data(**kwargs)
        context['upload_form'] = eloboosted_forms.ImageForm
        return context


class ChatPage(ChatUsersMixin, TemplateView):
    template_name = 'usermanagement/chat.html'


class UploadImageFromProfile(CreateView):
    template_name = 'usermanagement/profile.html'
    form_class = eloboosted_forms.ImageForm

    def get_context_data(self, **kwargs):
        context = super(UploadImageFromProfile, self).get_context_data(**kwargs)
        context['upload_form'] = context.pop('form')
        return context

    def form_valid(self, form):
        image = form.save(commit=False)
        image.owner = self.request.user
        image.save()
        log_image_upload(self.request, image)
        messages.success(self.request, _('Image successfully uploaded and sent for moderation.'))
        return HttpResponseRedirect(reverse('usermanagement:profile'))

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        context['upload_form_invalid'] = True
        return self.render_to_response(context)


def delete_image(request, pk):
    image = get_object_or_404(eloboosted_models.Image, pk=pk)
    if image not in request.user.image_set.all():
        return HttpResponse('it\'s not your image!')
    image.owner = None
    image.save()
    messages.success(request, _('Image successfully removed.'))
    return HttpResponseRedirect(reverse('usermanagement:profile'))


def privacy_settings(request):
    allow_messages = False
    allow_see_all_images = False
    has_changed = False
    if request.POST.get('allow_messages', ''):
        allow_messages = True
    if request.POST.get('allow_see_all_images', ''):
        allow_see_all_images = True
    if allow_messages != request.user.allow_messages:
        has_changed = True
        request.user.allow_messages = allow_messages
    if allow_see_all_images != request.user.allow_see_all_images:
        has_changed = True
        request.user.allow_see_all_images = allow_see_all_images
    if has_changed:
        request.user.save()
    messages.success(request, _('Privacy settings saved.'))
    return HttpResponseRedirect(reverse('usermanagement:profile'))


class FavoriteImages(TemplateView):
    template_name = 'usermanagement/favorites.html'


def toggle_favorite(request, operation):
    if request.is_ajax():
        image_pk = request.POST.get('image_pk', '')
        if image_pk:
            image = get_object_or_404(eloboosted_models.Image.moderated_objects, pk=image_pk)
            if image.owner != request.user:
                status = 'error'
                if operation == 'add':
                    if image not in request.user.favorite_images.all():
                        request.user.favorite_images.add(image)
                        status = 'success'
                elif operation == 'remove':
                    if image in request.user.favorite_images.all():
                        request.user.favorite_images.remove(image)
                        status = 'success'
                return HttpResponse(json.dumps({'status': status}))


class Chat(ChatUsersMixin, ListView):
    template_name = 'usermanagement/chat.html'
    model = models.Message
    context_object_name = 'chat_messages'
    companion = None
    form = MessageForm

    def get_context_data(self, **kwargs):
        context = super(Chat, self).get_context_data(**kwargs)
        context['companion'] = self.companion
        if 'form' in kwargs:
            context['form'] = kwargs['form']
        else:
            context['form'] = self.form
        return context

    def post(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        form = self.form(request.POST, request.FILES)
        if form.is_valid():
            msg = form.save(commit=False)
            msg.sender = self.request.user
            msg.receiver = get_object_or_404(models.MyUser, pk=self.kwargs.get('user_pk'))
            msg.save()
            return HttpResponseRedirect(reverse('usermanagement:chat', kwargs={'user_pk': self.kwargs.get('user_pk')}))
        else:
            context = self.get_context_data(form=form)
            return self.render_to_response(context)

    def get_queryset(self):
        companion = get_object_or_404(models.MyUser, pk=self.kwargs.get('user_pk'))
        user = self.request.user

        conversation_messages = self.model.objects.filter(
            (Q(sender=user) & Q(receiver=companion)) | (Q(sender=companion) & Q(receiver=user)))

        if not conversation_messages or companion == user:
            raise Http404
        self.companion = companion
        self.model.objects.filter(Q(sender=companion) & Q(receiver=user) & Q(is_read=False)).update(is_read=True)
        return conversation_messages


def transfer_likes(request):
    if request.is_ajax():
        try:
            amount = int(request.POST.get('amount'))
            if amount <= 0:
                raise ValueError('amount must be positive!')
            if amount > request.user.likes_balance:
                raise ValueError('can\'t donate more than you\'ve got!')
            image = get_object_or_404(eloboosted_models.Image.moderated_objects, pk=request.POST.get('image_pk'))
            owner = image.owner
            models.LikesTransfer.objects.create(
                from_user=request.user,
                to_user=owner,
                amount=amount
            )
            status = 'success'
            message = _('Success!')
        except Exception as e:
            message = _('Amount of likes must be greater than 0 and lower than ')
            status = 'error'

        return HttpResponse(json.dumps({'status': status, 'message': message,
                                        }))


def check_on_login(request):
    request.session.pop('image_1_pk', None)
    request.session.pop('image_2_pk', None)
    return HttpResponseRedirect(reverse('usermanagement:profile'))


def check_on_logout(request):
    request.session['have_18_age'] = 'True'
    return HttpResponseRedirect(reverse('account_login'))


class LikesPage(TemplateView):
    template_name = 'usermanagement/likes.html'


def paypal_callback_success(sender, **kwargs):
    ipn_obj = sender
    if ipn_obj.payment_status == ST_PP_COMPLETED:
        user_pk = int(ipn_obj.custom)
        user = models.MyUser.objects.get(pk=user_pk)
        amount = ipn_obj.quantity
        models.LikesBuying.objects.create(
            payment=ipn_obj,
            user=user,
            amount=amount
        )


valid_ipn_received.connect(paypal_callback_success)

templates/usermanagement/modals/buy_likes.html
{% load i18n %}
<div class="modal fade" id="buy_likes_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">{% trans 'Buy likes' %}</h4>
            </div>
            <div class="modal-body">
                <form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post"
                      target="_top">
                    <input type="hidden" name="cmd" value="_s-xclick">
                    <input type="hidden" name="hosted_button_id" value="UDSKGB363GN7U">
                    <input type="hidden" name="custom" value="{{ request.user.pk }}">

                    <div class="form-group">
                        <label>{% trans "Amount" %}</label>
                        <input class="form-control" type="number" name="quantity" value="1" min="1">
                    </div>
                    {#  qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq  #}
                    <input type="image" src="https://www.sandbox.paypal.com/ru_RU/RU/i/btn/btn_buynowCC_LG.gif"
                           border="0"
                           name="submit" alt="PayPal — более безопасный и легкий способ оплаты через Интернет!">
                    {#  qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq  #}
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
            </div>
        </div>
    </div>
</div>

templates/usermanagement/modals/delete.html
{% load i18n %}
<div class="modal fade" id="delete_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">{% trans "Are you sure you want to remove this image?" %}</h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
                <a id="delete_link" href="#" class="btn btn-danger">{% trans "Remove" %}</a>
            </div>
        </div>
    </div>
</div>

templates/usermanagement/modals/have_18_age.html
<!-- Modal -->
{% load i18n %}
<div class="modal fade" id="18_age_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title text-center">{% trans "Are you 18 years old?" %}</h3>
            </div>
            <div class="modal-footer center">
                <a href="https://www.google.ru/" class="btn btn-default ">{% trans "No" %}</a>
                <a href="{% url 'usermanagement:have_18_age' %}" class="btn btn-primary ">{% trans "Yes" %}</a>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('#18_age_modal').modal({
        'show': true,
        'backdrop': false,
        'keyboard': false
    })
</script>

templates/usermanagement/modals/images_of_user.html
<div class="modal fade" id="images_of_user_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content" id="images_of_user_modal_content">

        </div>
    </div>
</div>

templates/usermanagement/modals/likes.html
{% load i18n %}
<div class="modal fade" id="transfer_likes_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">{% trans "Transfer likes to user" %} <span id="likes_to_user"></span></h4>
            </div>
            <div class="modal-body">
                <div class="form-inline">
                    <div class="form-group">
                        <label class="control-label">{% trans "Enter amount of likes" %}: <input type="number"
                                                                                                 name="amount"
                                                                                                 id="likes_amount"
                                                                                                 max="{{ request.user.likes_balance }}"
                                                                                                 min="1"
                                                                                                 class="form-control"></label>

                        <p class="help-block">{% trans "Balance" %}: <span
                                id="likes_balance">{{ request.user.likes_balance }}</span></p>
                    </div>
                    <input type="hidden" name="image_pk" id="image_pk_for_likes">
                </div>
                <div id="likes_response"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
                    <button type="button" class="btn btn-primary" onclick="transfer_likes(this)"
                            data-loading-text="Отправка..." autocomplete="off">{% trans "Transfer" %}
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

templates/usermanagement/modals/out_likes.html
<div class="modal fade" id="out_likes_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Вывести лайки</h4>
            </div>
            <div class="modal-body">
                <form class="form-inline" action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post"
                      target="_top">
                    <input type="hidden" name="cmd" value="_s-xclick">
                    <input type="hidden" name="hosted_button_id" value="UDSKGB363GN7U">
                    <input type="hidden" name="custom" value="{{ request.user.pk }}">

                    <div class="form-group">
                        <label>Количество</label>
                        <input class="form-control" type="number" name="quantity" value="1" min="1">
                    </div>
                    <input type="image" src="https://www.sandbox.paypal.com/ru_RU/RU/i/btn/btn_buynowCC_LG.gif"
                           border="0"
                           name="submit" alt="PayPal — более безопасный и легкий способ оплаты через Интернет!">

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

templates/usermanagement/modals/send_message.html
{% load i18n %}
<div class="modal fade" id="send_message_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">{% trans "Send message to user" %} <span id="message_to_user"></span></h4>
            </div>
            <div class="modal-body">
                <form id="message_data" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>{% trans "Message text" %}<textarea id="message_textarea" name="text" class="form-control"
                                                        cols="100"
                                                        rows="5"></textarea></label>
                    </div>

                    <div class="form-group">
                        <input accept="image/*" class="file-input" id="message_attached_image" name="attached_image"
                               type="file">
                    </div>
                    <input type="hidden" name="image_pk" id="image_pk_for_message">
                </form>
                <div id="message_response"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
                    <button type="button" class="btn btn-primary" onclick="send_message(this)"
                            data-loading-text="Отправка..." autocomplete="off">{% trans "Send" %}
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

templates/usermanagement/modals/upload.html
{% load i18n %}
<div class="modal fade" id="upload_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">{% trans "Upload image" %}</h4>
            </div>

                {% if request.user.get_images_count < 3 %}
                    <form action="{% url 'usermanagement:upload' %}" method="post" enctype="multipart/form-data">
                    <div class="modal-body">
                        {% include 'forms/upload.html' with form=upload_form %}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
                        <button type="submit" class="btn btn-primary">{% trans "Upload" %}</button>
                    </div>
                    </form>
                {% endif %}
        </div>
    </div>
</div>
{% if upload_form_invalid %}
    <script>
        $('#upload_modal').modal({'show': true})
    </script>
{% endif %}